repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: detect-private-key
  - id: pretty-format-json
  - id: requirements-txt-fixer

- repo: https://github.com/psf/black
  rev: 22.10.0
  hooks:
  - id: black

# Lint Python code
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.4.4
  hooks:
  - id: ruff
    args: ["--fix"]  # optional, auto-fix simple issues

# Ensure no debug prints or debugger breakpoints
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: debug-statements

# Sort Python imports
- repo: https://github.com/PyCQA/isort
  rev: 6.0.1
  hooks:
  - id: isort
